[build]
command = "echo Building Functions"
# command = "npm run build"

[functions]
node_bundler = "esbuild"
external_node_modules = ["fastify"]

[[redirects]]
force = true
from = "/*"
status = 200
to = "/.netlify/functions/server/:splat"
